
STD_PROTOCOL_IF_MKFILES_DIR := $(dir $(lastword $(MAKEFILE_LIST)))
STD_PROTOCOL_IF_DIR := $(abspath $(STD_PROTOCOL_IF_MKFILES_DIR)/..)

STD_PROTOCOL_IF:=$(STD_PROTOCOL_IF_DIR)
export STD_PROTOCOL_IF

ifneq (1,$(RULES))

STD_PROTOCOL_IF_JAR = $(STD_PROTOCOL_IF_DIR)/lib/std_protocol_if.jar

STD_PROTOCOL_IF_DEPS = $(CHISELLIB_JARS)

STD_PROTOCOL_IF_JARS = $(STD_PROTOCOL_IF_JAR) $(STD_PROTOCOL_IF_DEPS)

else # Rules

endif

